In [13]:
import numpy as np
import json

In [14]:
path = "/Users/stanislavsmirnov/Documents/Github_local/Sizeable_datasets/yelp_academic_dataset_review.json"
f = open(path)

In [15]:
dataset = []

In [16]:
while len(dataset) < 50000:
    dataset.append(json.loads(f.readline()))

In [17]:
dataset[0]

{'review_id': 'xQY8N_XvtGbearJ5X4QryQ',
 'user_id': 'OwjRMXRC0KyPrIlcjaXeFQ',
 'business_id': '-MhfebM0QIsKt87iDN-FNw',
 'stars': 2.0,
 'useful': 5,
 'funny': 0,
 'cool': 0,
 'text': 'As someone who has worked with many museums, I was eager to visit this gallery on my most recent trip to Las Vegas. When I saw they would be showing infamous eggs of the House of Faberge from the Virginia Museum of Fine Arts (VMFA), I knew I had to go!\n\nTucked away near the gelateria and the garden, the Gallery is pretty much hidden from view. It\'s what real estate agents would call "cozy" or "charming" - basically any euphemism for small.\n\nThat being said, you can still see wonderful art at a gallery of any size, so why the two *s you ask? Let me tell you:\n\n* pricing for this, while relatively inexpensive for a Las Vegas attraction, is completely over the top. For the space and the amount of art you can fit in there, it is a bit much.\n* it\'s not kid friendly at all. Seriously, don\'t bring them.

In [18]:
ratings = [d['stars'] for d in dataset]

In [19]:
cool = [d['cool'] for d in dataset]

In [20]:
funny = [d['funny'] for d in dataset]

In [21]:
useful = [d['useful'] for d in dataset]

In [22]:
# convert lists to numpy array

ratings = np.array(ratings)
cool = np.array(cool)
funny = np.array(funny)
useful = np.array(useful)

In [23]:
ratings

array([2., 1., 5., ..., 5., 3., 1.])

In [24]:
np.mean(ratings)

3.751

In [25]:
np.var(ratings)

2.055919

In [26]:
# N-d array

np.stack([cool, funny, useful])

array([[0, 0, 0, ..., 2, 0, 0],
       [0, 1, 0, ..., 1, 0, 0],
       [5, 1, 1, ..., 1, 0, 0]])

In [28]:
features = np.stack([cool, funny, useful]).T
features

array([[0, 0, 5],
       [0, 1, 1],
       [0, 0, 1],
       ...,
       [2, 1, 1],
       [0, 0, 0],
       [0, 0, 0]])

In [30]:
# with an array most operations (in particularly multiplication) are overloaded to "elementwise" operations.
# for many linear algebra routines, it is more convinient to use "matrix" type instead.

features = np.matrix(features)
features

matrix([[0, 0, 5],
        [0, 1, 1],
        [0, 0, 1],
        ...,
        [2, 1, 1],
        [0, 0, 0],
        [0, 0, 0]])

In [31]:
features.T * features

matrix([[114026,  78285, 140867],
        [ 78285,  97344, 115658],
        [140867, 115658, 342220]])

In [32]:
# matrix inverse

np.linalg.inv(features.T * features)

matrix([[ 2.50707986e-05, -1.32020896e-05, -5.85798877e-06],
        [-1.32020896e-05,  2.41177994e-05, -2.71660830e-06],
        [-5.85798877e-06, -2.71660830e-06,  6.25151887e-06]])

In [35]:
# some complex math on matrixes
2 * np.sin(features) + 3

matrix([[3.        , 3.        , 1.08215145],
        [3.        , 4.68294197, 4.68294197],
        [3.        , 3.        , 4.68294197],
        ...,
        [4.81859485, 4.68294197, 4.68294197],
        [3.        , 3.        , 3.        ],
        [3.        , 3.        , 3.        ]])

In [36]:
2 * np.sin(features) + 3 > 4

matrix([[False, False, False],
        [False,  True,  True],
        [False, False,  True],
        ...,
        [ True,  True,  True],
        [False, False, False],
        [False, False, False]])

In [37]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])